build:
  version: "3.0"

cards:
  message: "welcome to cardoBank cards related prod APIs"
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@cardobank.com"
  onCallSupport:
    - (453) 392-4829
    - (453) 203-0384

