build:
  version: "2.0"

cards:
  message: "welcome to cardoBank cards related QA APIs"
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@cardobank.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 523-1345
