spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "welcome to cardoBank loans related prod APIs"
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    emai: "aishwarya@cardobank.com"
  onCallSupport:
    - (453) 392-4829
    - (453) 203-0384

