name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - '3.Ticketing/auth/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t generatltest/auth .
      - run: docker login -u $DOCKER_USERNAME -P $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ DOCKER_PASSWORD }}
      - run: docker push generatltest/auth 
          
    
   
