name: tests-payment

on:
  pull_request
    paths:
      - '3.Ticketing/payments/**'	
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd 3.Ticketing/payments && npm install && npm run test:ci
